name: Daily test & build
on:
  workflow_dispatch:
  push: 
    branches: 
      - current
env:
  ## Sets environment variable
  TARGET_BUILD: x86_64-linux
  PARALEL: 1
  RETENTION_DAYS_BINS: 3
  RUN_SCENARIOUS_PARALEL: true
  ## TODO: add ldc2/dmd switch & version
jobs:
  build_and_unittest:
    runs-on: self-hosted
    steps:
      - name: Cleanup
        run: |
          sudo rm -rf *
          sudo rm -rf .git
          sudo rm -rf .github
          sudo rm -rf .vscode
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create build dir
        run: |
            mkdir -p ./build/${{ env.TARGET_BUILD }}
      - uses: actions/cache/restore@v3
        id: cache-restore
        with:
          path: |
            ./build/${{ env.TARGET_BUILD }}/tmp
            ./build/${{ env.TARGET_BUILD }}/lib
          key: ${{ runner.os }}-${{ hashFiles('./src/wrap-**') }}
      - name: Run unittests
        run: |
          source ~/.bashrc
          make unittest ${{ env.PARALEL }}

      - name: Check unittests
        run: cat logs/${{ env.TARGET_BUILD }}/unittest.log | grep -E "^[0-9]+ modules passed unittests"

      - name: Report unittests
        if: success()
        run: |
          RESULT=$(cat logs/${{ env.TARGET_BUILD }}/unittest.log | grep -E "^[0-9]+ modules passed unittests")
          echo -e "### :heavy_check_mark: Unittests passed \n $RESULT" >> $GITHUB_STEP_SUMMARY
      
      - name: Report unittests
        if: failure()
        run: |
          RESULT=$(cat logs/${{ env.TARGET_BUILD }}/unittest.log | grep FAILED)
          echo -e "### :heavy_exclamation_mark: Unittests passed \n $RESULT" >> $GITHUB_STEP_SUMMARY

      - name: Run Bdd tests
        run: |
          source ~/.bashrc
          make bddtest TEST_STAGE=commit | tail -n 3 | sed 's/\x1B\[[0-9;]*[a-zA-Z]//g' > bddconsole.log

      - name: Create bdd result
        run: |
          for i in ./logs/${{ env.TARGET_BUILD }}/bdd/results/*.json; do cat $i | jq '.info.name,.info.result.outcome."$@",.info.result.outcome.msg?'; done  | sed 'N;N;s/\n/ - /g' |  tr -d '"' | sed s/"- null"// > ./bddresult.log
      
      - name: Report Bdd result
        run: |
          cat ./bddresult.log >> $GITHUB_STEP_SUMMARY

      - name: Check bdd result
        run: cat ./bddconsole.log | tail -n 1 | grep -E "Test result success!"

      - name: Build
        run: |
          source ~/.bashrc
          make tagion -j ${{ env.PARALEL }}
          make bddenv          
      
      - name: Create passed tag
        if: success() && (github.ref == 'refs/heads/current')
        uses: rickstaa/action-create-tag@v1
        with:
          tag: "passed"
          force_push_tag: true

      - name: Create failed tag
        if: failure() && (github.ref == 'refs/heads/current')
        uses: rickstaa/action-create-tag@v1
        with:
          tag: "failed"
          force_push_tag: true


      - uses: actions/cache/save@v3
        if: steps.cache-restore.outputs.cache-hit != 'true'
        with:
          path: |
            ./build/${{ env.TARGET_BUILD }}/tmp
            ./build/${{ env.TARGET_BUILD }}/lib
          key: ${{ steps.cache-restore.outputs.cache-primary-key }}
      - name: Create upload dir
        run: |
            mkdir -p ./upload/bdd
            cp -rf ./build/${{ env.TARGET_BUILD }}/bin/tagion ./upload/
            cp -rf ./build/${{ env.TARGET_BUILD }}/bin/testbench ./upload/            
            cp -rf ./build/${{ env.TARGET_BUILD }}/bin/collider ./upload/
            cp -rf ./logs/${{ env.TARGET_BUILD }}/bdd/* ./upload/bdd/
            cp -rf ./logs/${{ env.TARGET_BUILD }}/unittest.log ./upload/
            cp -rf ./fundamental ./upload/
            cp -rf ./bdd ./upload/
      - name: Upload all
        uses: actions/upload-artifact@v3
        with:
          name: bins-logs
          path: |
            ./upload
          retention-days: ${{ env.RETENTION_DAYS_BINS }}
      
    
    
